# Train Custom Model Using Scikit Learn

## 1 Read in Collected Data and Process

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('coords.csv')

In [3]:
df.head()

,class,x1,y1,z1,v1,x2,y2,z2,v2,x3,...,z39,x40,y40,z40,x41,y41,z41,x42,y42,z42
0,ለምን,0.483307,0.231578,-0.584007,0.999898,0.504416,0.190950,-0.522643,0.999848,0.517840,...,-0.012437,0.316636,0.094683,-0.014839,0.329152,0.073797,-0.012698,0.337913,0.056405,-0.009735
1,ለምን,0.483975,0.231873,-0.666048,0.999945,0.506448,0.185909,-0.607750,0.999922,0.518866,...,-0.012662,0.282908,0.103163,-0.014023,0.293204,0.082084,-0.011744,0.298867,0.063755,-0.009036
2,ለምን,0.487058,0.233701,-0.761830,0.999960,0.509176,0.187470,-0.702055,0.999946,0.521292,...,-0.013867,0.266984,0.125805,-0.015711,0.279040,0.104032,-0.012874,0.286753,0.086279,-0.009617
3,ለምን,0.485298,0.236616,-0.635450,0.999879,0.509198,0.193196,-0.576642,0.999811,0.521744,...,-0.013636,0.268645,0.147987,-0.014783,0.282323,0.126132,-0.011023,0.292056,0.107455,-0.006730
4,ለምን,0.486986,0.238980,-0.642063,0.999903,0.510983,0.196924,-0.584852,0.999845,0.523073,...,-0.013496,0.272989,0.153211,-0.013506,0.287043,0.131331,-0.009840,0.296500,0.113409,-0.006386

In [4]:
df.tail()

,class,x1,y1,z1,v1,x2,y2,z2,v2,x3,...,z39,x40,y40,z40,x41,y41,z41,x42,y42,z42
12080,የት,0.534056,0.247431,-0.401932,0.999991,0.545345,0.227671,-0.369693,0.999989,0.553319,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
12081,የት,0.533021,0.249829,-0.358024,0.999996,0.544841,0.229273,-0.324978,0.999995,0.552880,...,-0.009177,0.450267,0.565148,-0.010875,0.455993,0.566434,-0.011083,0.461179,0.567334,-0.011227
12082,የት,0.532423,0.250117,-0.404204,0.999993,0.544494,0.229105,-0.371443,0.999992,0.552492,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
12083,የት,0.534501,0.256408,-0.477381,0.999995,0.546895,0.236940,-0.447860,0.999994,0.554695,...,-0.003266,0.393467,0.546953,-0.004190,0.387347,0.544067,-0.003821,0.382063,0.541462,-0.003313
12084,የት,0.534007,0.256969,-0.492999,0.999997,0.546678,0.237555,-0.464415,0.999996,0.554474,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [18]:
df[df['class']=='የት']

,class,x1,y1,z1,v1,x2,y2,z2,v2,x3,...,z39,x40,y40,z40,x41,y41,z41,x42,y42,z42
11917,የት,0.584528,0.247539,-0.966274,0.999893,0.604424,0.196364,-0.932584,0.999785,0.617555,...,-0.046919,0.418709,0.733896,-0.059171,0.432476,0.710305,-0.059906,0.445513,0.685696,-0.060845
11918,የት,0.592068,0.241027,-1.094694,0.999907,0.608510,0.191237,-1.060099,0.999815,0.621394,...,-0.043501,0.407288,0.724741,-0.056914,0.420618,0.696745,-0.059133,0.432238,0.669074,-0.060243
11919,የት,0.590989,0.242210,-1.116550,0.999918,0.608009,0.191626,-1.082000,0.999842,0.621085,...,-0.039020,0.408575,0.719246,-0.054279,0.421382,0.693466,-0.057664,0.432994,0.667653,-0.059029
11920,የት,0.565651,0.375589,-0.462765,0.999996,0.588227,0.329426,-0.413935,0.999997,0.602684,...,-0.013909,0.247903,0.768904,-0.020469,0.236868,0.776837,-0.022820,0.227166,0.787183,-0.024644
11921,የት,0.574179,0.371703,-0.525541,0.999993,0.593908,0.326033,-0.480090,0.999995,0.608296,...,-0.041613,0.298811,0.775641,-0.057490,0.294913,0.780603,-0.065251,0.290358,0.787454,-0.071049
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12080,የት,0.534056,0.247431,-0.401932,0.999991,0.545345,0.227671,-0.369693,0.999989,0.553319,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
12081,የት,0.533021,0.249829,-0.358024,0.999996,0.544841,0.229273,-0.324978,0.999995,0.552880,...,-0.009177,0.450267,0.565148,-0.010875,0.455993,0.566434,-0.011083,0.461179,0.567334,-0.011227
12082,የት,0.532423,0.250117,-0.404204,0.999993,0.544494,0.229105,-0.371443,0.999992,0.552492,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
12083,የት,0.534501,0.256408,-0.477381,0.999995,0.546895,0.236940,-0.447860,0.999994,0.554695,...,-0.003266,0.393467,0.546953,-0.004190,0.387347,0.544067,-0.003821,0.382063,0.541462,-0.003313
12084,የት,0.534007,0.256969,-0.492999,0.999997,0.546678,0.237555,-0.464415,0.999996,0.554474,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [6]:
X = df.drop('class', axis=1) # features
y = df['class'] # target value

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1234)

In [8]:
y_test

3185           ምን
10534        መብላት
4448           ምን
7362     መታጠቢያ ቤት
11267     አመሰግናለሁ
           ...
9697         መብላት
1794           ምን
3609           ምን
4792      nothing
3386           ምን
Name: class, Length: 3626, dtype: object

## 2 Train Machine Learning Classification Model

In [9]:
from sklearn.pipeline import make_pipeline 
from sklearn.preprocessing import StandardScaler 

from sklearn.linear_model import LogisticRegression, RidgeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

In [10]:
pipeline = make_pipeline(StandardScaler(), RandomForestClassifier(),verbose=True)

In [11]:
model = pipeline.fit(X_train, y_train)

[Pipeline] .... (step 1 of 2) Processing standardscaler, total=   0.1s
[Pipeline]  (step 2 of 2) Processing randomforestclassifier, total=   5.9s

In [13]:
model.predict(X_test)

array(['ምን', 'መብላት', 'ምን', ..., 'ምን', 'nothing', 'ምን'], dtype=object)

## 3 Evaluate and Serialize Model

In [14]:
import sklearn.metrics as metrics
import pickle

In [15]:
yhat = model.predict(X_test)

In [16]:
print(metrics.accuracy_score(y_test,yhat))
print(metrics.balanced_accuracy_score(y_test,yhat))
#print(metrics.recall_score(y_test,yhat,average="samples",labels=['ለምን','nothing','ምን','መቼ']))

0.9931053502482073
0.9699873255192528

In [17]:
y_test

3185           ምን
10534        መብላት
4448           ምን
7362     መታጠቢያ ቤት
11267     አመሰግናለሁ
           ...
9697         መብላት
1794           ምን
3609           ምን
4792      nothing
3386           ምን
Name: class, Length: 3626, dtype: object

In [19]:
with open('ETHSLv4.pkl', 'wb') as f:
    pickle.dump(model, f)